### ISSUE TITLE
Table Links

### ISSUE THREAD

**Issue by packytagliaferro** [lloricode/laravel-html-table#2]
This package is perfect for building admins on the fly but can you add links? Lets say I export all the blog posts like: 

My Controller

```
$model 	= 'App\Post';
		$title 	= ['Title'];
		$fields = ['title'];

		
		return view('admin.dashboard',
        [
			'title' => $title,
			'model' => $model,
			'fields' => $fields
		]);
```

My View

```
{!! Table::generateTableFromModel(
                $title,  // Column for table
                $model,
                $fields, // Fields from model
                20) 
            !!}   

```
I would to add a link to the table row using `$post->slug`.

**Comment by lloricode** [comment]
@packytagliaferro 

hmm maybe i will add this feature as your request :) 

i will work for this, or you can make a PR if you want :)

Regards :+1:

**Comment by lloricode** [comment]
@packytagliaferro, ive already release for your suggestion, can you try now?
